import SideBar from "@/components/SideBar/SideBar";

export const metadata = {
  title: "Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen">
          <SideBar />
          <main className="container mx-auto flex-1 p-8">{children}</main>
        </div>
      </body>
    </html>
  );
}
