import SideBar from "@/components/SideBar/SideBar";

export const metadata = {
  title: "Dashborad",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <div className="flex min-h-screen">
      <SideBar />
      <main className="container mx-auto flex-1 p-8">{children}</main>
    </div>
  );
}
